import {
  BsHouseDoor,
  BsPerson,
  BsPersonCircle,
  BsPencilSquare,
  BsGear,
  BsShieldLock,
  BsBell,
  BsCart,
  BsBag,
  BsBagCheck,
  BsBagPlus,
  BsCreditCard,
  BsFileEarmarkText,
  BsFileEarmarkPdf,
  BsFileEarmarkWord,
  BsBarChart,
  BsGraphUp,
  BsGraphDown,
  BsPeople,
  BsChatDots,
  BsEnvelope,
  BsEnvelopeOpen,
  BsEnvelopeFill,
  BsCalendar,
  BsCalendarCheck,
  BsCalendar2Event,
  BsQuestionCircle,
  BsInfoCircle,
  BsChatSquareQuote,
  BsBook,
  BsBriefcase,
  BsBuilding,
  BsCamera,
  BsCloud,
  BsHeart,
  BsKey,
  BsLaptop,
  BsLightning,
  BsMegaphone,
} from "react-icons/bs";

export const sidebarMenu = [
  {
    icon: <BsHouseDoor />,
    title: "Home",
    isOpen: false,
    children: [],
    link: "/home",
  },
  {
    icon: <BsPerson />,
    title: "Profile",
    isOpen: false,
    children: [
      {
        icon: <BsPersonCircle />,
        title: "View Profile",
        isOpen: false,
        children: [],
        link: "/profile/view",
      },
      {
        icon: <BsPencilSquare />,
        title: "Edit Profile",
        isOpen: false,
        children: [],
        link: "/profile/edit",
      },
    ],
    link: "/profile",
  },
  {
    icon: <BsGear />,
    title: "Settings",
    isOpen: false,
    children: [
      {
        icon: <BsShieldLock />,
        title: "Privacy",
        isOpen: false,
        children: [],
        link: "/settings/privacy",
      },
      {
        icon: <BsBell />,
        title: "Notifications",
        isOpen: false,
        children: [],
        link: "/settings/notifications",
      },
    ],
    link: "/settings",
  },
  {
    icon: <BsCart />,
    title: "Shop",
    isOpen: false,
    children: [
      {
        icon: <BsBag />,
        title: "Products",
        isOpen: false,
        children: [
          {
            icon: <BsBagCheck />,
            title: "Categories",
            isOpen: false,
            children: [],
            link: "/shop/products/categories",
          },
          {
            icon: <BsBagPlus />,
            title: "New Arrivals",
            isOpen: false,
            children: [],
            link: "/shop/products/new",
          },
        ],
        link: "/shop/products",
      },
      {
        icon: <BsCreditCard />,
        title: "Cart",
        isOpen: false,
        children: [],
        link: "/shop/cart",
      },
    ],
    link: "/shop",
  },
  {
    icon: <BsFileEarmarkText />,
    title: "Documents",
    isOpen: false,
    children: [
      {
        icon: <BsFileEarmarkPdf />,
        title: "Reports",
        isOpen: false,
        children: [],
        link: "/documents/reports",
      },
      {
        icon: <BsFileEarmarkWord />,
        title: "Letters",
        isOpen: false,
        children: [],
        link: "/documents/letters",
      },
    ],
    link: "/documents",
  },
  {
    icon: <BsBarChart />,
    title: "Analytics",
    isOpen: false,
    children: [
      {
        icon: <BsGraphUp />,
        title: "Sales",
        isOpen: false,
        children: [],
        link: "/analytics/sales",
      },
      {
        icon: <BsGraphDown />,
        title: "Expenses",
        isOpen: false,
        children: [],
        link: "/analytics/expenses",
      },
    ],
    link: "/analytics",
  },
  {
    icon: <BsPeople />,
    title: "Community",
    isOpen: false,
    children: [
      {
        icon: <BsChatDots />,
        title: "Forums",
        isOpen: false,
        children: [],
        link: "/community/forums",
      },
      {
        icon: <BsPeople />,
        title: "Members",
        isOpen: false,
        children: [],
        link: "/community/members",
      },
    ],
    link: "/community",
  },
  {
    icon: <BsEnvelope />,
    title: "Messages",
    isOpen: false,
    children: [
      {
        icon: <BsEnvelopeOpen />,
        title: "Inbox",
        isOpen: false,
        children: [],
        link: "/messages/inbox",
      },
      {
        icon: <BsEnvelopeFill />,
        title: "Sent",
        isOpen: false,
        children: [],
        link: "/messages/sent",
      },
    ],
    link: "/messages",
  },
  {
    icon: <BsCalendar />,
    title: "Events",
    isOpen: false,
    children: [
      {
        icon: <BsCalendarCheck />,
        title: "Upcoming",
        isOpen: false,
        children: [],
        link: "/events/upcoming",
      },
      {
        icon: <BsCalendar2Event />,
        title: "Past",
        isOpen: false,
        children: [],
        link: "/events/past",
      },
    ],
    link: "/events",
  },
  {
    icon: <BsQuestionCircle />,
    title: "Help",
    isOpen: false,
    children: [
      {
        icon: <BsInfoCircle />,
        title: "FAQ",
        isOpen: false,
        children: [],
        link: "/help/faq",
      },
      {
        icon: <BsChatSquareQuote />,
        title: "Support",
        isOpen: false,
        children: [],
        link: "/help/support",
      },
    ],
    link: "/help",
  },
  {
    icon: <BsBook />,
    title: "Library",
    isOpen: false,
    children: [
      {
        icon: <BsBook />,
        title: "Books",
        isOpen: false,
        children: [],
        link: "/library/books",
      },
      {
        icon: <BsBook />,
        title: "Journals",
        isOpen: false,
        children: [],
        link: "/library/journals",
      },
    ],
    link: "/library",
  },
  {
    icon: <BsBriefcase />,
    title: "Careers",
    isOpen: false,
    children: [
      {
        icon: <BsBriefcase />,
        title: "Job Listings",
        isOpen: false,
        children: [],
        link: "/careers/jobs",
      },
      {
        icon: <BsBriefcase />,
        title: "Internships",
        isOpen: false,
        children: [],
        link: "/careers/internships",
      },
    ],
    link: "/careers",
  },
  {
    icon: <BsBuilding />,
    title: "Departments",
    isOpen: false,
    children: [
      {
        icon: <BsBuilding />,
        title: "HR",
        isOpen: false,
        children: [],
        link: "/departments/hr",
      },
      {
        icon: <BsBuilding />,
        title: "Finance",
        isOpen: false,
        children: [],
        link: "/departments/finance",
      },
    ],
    link: "/departments",
  },
  {
    icon: <BsCamera />,
    title: "Gallery",
    isOpen: false,
    children: [
      {
        icon: <BsCamera />,
        title: "Photos",
        isOpen: false,
        children: [],
        link: "/gallery/photos",
      },
      {
        icon: <BsCamera />,
        title: "Videos",
        isOpen: false,
        children: [],
        link: "/gallery/videos",
      },
    ],
    link: "/gallery",
  },
  {
    icon: <BsCloud />,
    title: "Cloud Services",
    isOpen: false,
    children: [
      {
        icon: <BsCloud />,
        title: "Storage",
        isOpen: false,
        children: [],
        link: "/cloud/storage",
      },
      {
        icon: <BsCloud />,
        title: "Computing",
        isOpen: false,
        children: [],
        link: "/cloud/computing",
      },
    ],
    link: "/cloud",
  },
  {
    icon: <BsHeart />,
    title: "Favorites",
    isOpen: false,
    children: [
      {
        icon: <BsHeart />,
        title: "Saved Items",
        isOpen: false,
        children: [],
        link: "/favorites/saved",
      },
      {
        icon: <BsHeart />,
        title: "Liked Posts",
        isOpen: false,
        children: [],
        link: "/favorites/liked",
      },
    ],
    link: "/favorites",
  },
  {
    icon: <BsKey />,
    title: "Security",
    isOpen: false,
    children: [
      {
        icon: <BsKey />,
        title: "Password",
        isOpen: false,
        children: [],
        link: "/security/password",
      },
      {
        icon: <BsKey />,
        title: "2FA",
        isOpen: false,
        children: [],
        link: "/security/2fa",
      },
    ],
    link: "/security",
  },
  {
    icon: <BsLaptop />,
    title: "Devices",
    isOpen: false,
    children: [
      {
        icon: <BsLaptop />,
        title: "My Devices",
        isOpen: false,
        children: [],
        link: "/devices/my",
      },
      {
        icon: <BsLaptop />,
        title: "Add Device",
        isOpen: false,
        children: [],
        link: "/devices/add",
      },
    ],
    link: "/devices",
  },
  {
    icon: <BsLightning />,
    title: "Shortcuts",
    isOpen: false,
    children: [
      {
        icon: <BsLightning />,
        title: "Recent",
        isOpen: false,
        children: [],
        link: "/shortcuts/recent",
      },
      {
        icon: <BsLightning />,
        title: "Favorites",
        isOpen: false,
        children: [],
        link: "/shortcuts/favorites",
      },
    ],
    link: "/shortcuts",
  },
  {
    icon: <BsMegaphone />,
    title: "Announcements",
    isOpen: false,
    children: [
      {
        icon: <BsMegaphone />,
        title: "Company News",
        isOpen: false,
        children: [],
        link: "/announcements/company",
      },
      {
        icon: <BsMegaphone />,
        title: "Updates",
        isOpen: false,
        children: [],
        link: "/announcements/updates",
      },
    ],
    link: "/announcements",
  },
];
